# 3753. Total Waviness of Numbers in Range II

# You are given two integers num1 and num2 representing an inclusive range [num1, num2].
# The waviness of a number is defined as the total count of its peaks and valleys:
# A digit is a peak if it is strictly greater than both of its immediate neighbors.
# A digit is a valley if it is strictly less than both of its immediate neighbors.
# The first and last digits of a number cannot be peaks or valleys.
# Any number with fewer than 3 digits has a waviness of 0.
# Return the total sum of waviness for all numbers in the range [num1, num2].

# Example 1:
# Input: num1 = 120, num2 = 130
# Output: 3
# Explanation:
# In the range [120, 130]:
# 120: middle digit 2 is a peak, waviness = 1.
# 121: middle digit 2 is a peak, waviness = 1.
# 130: middle digit 3 is a peak, waviness = 1.
# All other numbers in the range have a waviness of 0.
# Thus, total waviness is 1 + 1 + 1 = 3.

# Example 2:
# Input: num1 = 198, num2 = 202
# Output: 3
# Explanation:
# In the range [198, 202]:
# 198: middle digit 9 is a peak, waviness = 1.
# 201: middle digit 0 is a valley, waviness = 1.
# 202: middle digit 0 is a valley, waviness = 1.
# All other numbers in the range have a waviness of 0.
# Thus, total waviness is 1 + 1 + 1 = 3.

# Example 3:
# Input: num1 = 4848, num2 = 4848
# Output: 2
# Explanation:
# Number 4848: the second digit 8 is a peak, and the third digit 4 is a valley, giving a waviness of 2.

# Constraints:
# 1 <= num1 <= num2 <= 1015​​​​​​​

class Solution(object):
    def totalWaviness(self, num1, num2):
        """
        :type num1: int
        :type num2: int
        :rtype: int
        """
        
        def solve(X):
            if X <= 0:
                return 0
            
            s = str(X)
            n = len(s)
            
            # Local memoization dictionary to keep state clean for each boundary
            memo = {}

            def dp(pos, tight, last, second_last, is_leading):
                # Base case: End of the string reached
                if pos == n:
                    return 1, 0

                state = (pos, tight, last, second_last, is_leading)
                if state in memo:
                    return memo[state]

                limit = int(s[pos]) if tight else 9
                total_count = 0
                total_wavy_sum = 0

                for digit in range(limit + 1):
                    new_tight = tight and (digit == limit)

                    if is_leading:
                        if digit == 0:
                            cnt, wav = dp(pos + 1, new_tight, -1, -1, True)
                        else:
                            cnt, wav = dp(pos + 1, new_tight, digit, -1, False)
                        
                        # CRITICAL FIX 1: We must accumulate the waviness from shorter numbers!
                        total_wavy_sum += wav
                        
                    else:
                        wavy_contribution = 0
                        if second_last != -1:
                            # Check if the current 'last' is a peak or a valley
                            if second_last < last > digit:
                                wavy_contribution = 1
                            elif second_last > last < digit:
                                wavy_contribution = 1

                        cnt, wav = dp(pos + 1, new_tight, digit, last, False)

                        # Accumulate the waviness of the suffix + the peak/valley we just found
                        total_wavy_sum += wav + (cnt * wavy_contribution)
                        
                        # CRITICAL FIX 2: Removed the rogue modulo operation here. 
                        # Python handles arbitrarily large integers automatically.

                    total_count += cnt

                memo[state] = (total_count, total_wavy_sum)
                return memo[state]

            # Start the recursion for the prefix
            _, ans = dp(0, True, -1, -1, True)
            return ans

        # Range Prefix Rule: [num1, num2] = solve(num2) - solve(num1 - 1)
        return solve(num2) - solve(num1 - 1)
    

'''
Generated by Gemini.ai. I couldnt figure it out and so I made use of the hints to generate an answer.
'''