# 3614. Process String with Special Operations II

# You are given a string s consisting of lowercase English letters and the special characters: '*', '#', and '%'.
# You are also given an integer k.
# Build a new string result by processing s according to the following rules from left to right:
# If the letter is a lowercase English letter append it to result.
# A '*' removes the last character from result, if it exists.
# A '#' duplicates the current result and appends it to itself.
# A '%' reverses the current result.
# Return the kth character of the final string result. If k is out of the bounds of result, return '.'.

# Example 1:
# Input: s = "a#b%*", k = 1
# Output: "a"
# Explanation:
# i	s[i]	Operation	Current result
# 0	'a'	Append 'a'	"a"
# 1	'#'	Duplicate result	"aa"
# 2	'b'	Append 'b'	"aab"
# 3	'%'	Reverse result	"baa"
# 4	'*'	Remove the last character	"ba"
# The final result is "ba". The character at index k = 1 is 'a'.

# Example 2:
# Input: s = "cd%#*#", k = 3
# Output: "d"
# Explanation:
# i	s[i]	Operation	Current result
# 0	'c'	Append 'c'	"c"
# 1	'd'	Append 'd'	"cd"
# 2	'%'	Reverse result	"dc"
# 3	'#'	Duplicate result	"dcdc"
# 4	'*'	Remove the last character	"dcd"
# 5	'#'	Duplicate result	"dcddcd"
# The final result is "dcddcd". The character at index k = 3 is 'd'.

# Example 3:
# Input: s = "z*#", k = 0
# Output: "."
# Explanation:
# i	s[i]	Operation	Current result
# 0	'z'	Append 'z'	"z"
# 1	'*'	Remove the last character	""
# 2	'#'	Duplicate the string	""
# The final result is "". Since index k = 0 is out of bounds, the output is '.'.

# Constraints:
# 1 <= s.length <= 105
# s consists of only lowercase English letters and special characters '*', '#', and '%'.
# 0 <= k <= 1015
# The length of result after processing s will not exceed 1015.

class Solution(object):
    def processStr(self, s, k):
        """
        :type s: str
        :type k: int
        :rtype: str
        """
        # dont actually need to do the doubling operations, just the others (doubling operations can be found using the modeulous for a section)
        # then given you have hit the k location, return the character by using the original string
        

        n = len(s)
        lengths = [0] * n
        current_length = 0
        
        # Pass 1: Track the virtual length at each index
        for i in range(n):
            if s[i] == '*': #remove char
                if current_length > 0:
                    current_length -= 1
            elif s[i] == '#': #double
                current_length *= 2
            elif s[i] == '%': #reverse
                # Reversing the string does not change its length
                current_length = current_length
            else: #added char
                current_length += 1
            lengths[i] = current_length
            
        # If k is out of bounds of the final generated string, return "."
        if k >= current_length or k < 0:
            return "."

        # Pass 2: Walk backwards to find the k-th character
        # k is 0-indexed based on LeetCode constraints.
        for i in range(n - 1, -1, -1):
            if lengths[i] == 0:
                continue

            if s[i] == '%':
                # Undo the reversal: mirror k across the current 0-indexed length
                k = lengths[i] - 1 - k
            elif s[i] == '#':
                # Undo the doubling. The previous length is what existed before this '#'
                prev_length = lengths[i-1] if i > 0 else 0
                if prev_length > 0 and k >= prev_length:
                    k -= prev_length
            elif s[i] == '*':
                # don't change k, just keep tracking. (it was previously longer)
                continue
            else:
                # K at this location
                if k == lengths[i] - 1:
                    return s[i]
                    
        return "." #empty string or there is no k-th character

'''
Generated by Gemini.ai, but following my ideas of how it should be appraoched.
'''