# 3474. Lexicographically Smallest Generated String

# You are given two strings, str1 and str2, of lengths n and m, respectively.
# A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:
# If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
# If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
# Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

# Example 1:
# Input: str1 = "TFTF", str2 = "ab"
# Output: "ababa"
# Explanation:
# The table below represents the string "ababa"
# Index	T/F	Substring of length m
# 0	'T'	"ab"
# 1	'F'	"ba"
# 2	'T'	"ab"
# 3	'F'	"ba"
# The strings "ababa" and "ababb" can be generated by str1 and str2.
# Return "ababa" since it is the lexicographically smaller string.

# Example 2:
# Input: str1 = "TFTF", str2 = "abc"
# Output: ""
# Explanation:
# No string that satisfies the conditions can be generated.

# Example 3:
# Input: str1 = "F", str2 = "d"
# Output: "a"

# Constraints:
# 1 <= n == str1.length <= 104
# 1 <= m == str2.length <= 500
# str1 consists only of 'T' or 'F'.
# str2 consists only of lowercase English characters.

class Solution(object):
    def generateString(self, str1, str2):
        """
        :type str1: str
        :type str2: str
        :rtype: str
        """
        n, m = len(str1), len(str2)
        ans = ["-"] * (n + m - 1)

        # fill all 'T' cases
        for i in range(n):
            if str1[i] == 'T':
                for j in range(m):
                    if ans[i + j] != "-" and ans[i + j] != str2[j]:
                        return ""
                    ans[i + j] = str2[j]

        # fill in remaining '-' and check F cases
        for i in range(n + m - 1):
            if ans[i] == "-":
                # Try 'a' first for lexicographical smallest
                ans[i] = 'a'
                
                # 'a' might not be the solution
                # We check all possible 'F' starting positions that cover index i
                if not self.isValid(ans, i, str1, str2):
                    ans[i] = 'b'
                    # If 'b' also fails, this configuration is impossible
                    if not self.isValid(ans, i, str1, str2):
                        return ""
        
        # all F cases must pass
        res = "".join(ans)
        for i in range(n):
            if str1[i] == 'F':
                if res[i:i+m] == str2:
                    return ""
            elif str1[i] == 'T':
                 if res[i:i+m] != str2:
                    return ""
                    
        return res

    def isValid(self, ans, curr_idx, str1, str2):
        """
        Checks if the character at curr_idx violates any 'F' 
        constraints in str1 that overlap with this position.
        This position may effect previous F cases
        """
        n, m = len(str1), len(str2)
        # check F's that contain this location
        for start in range(max(0, curr_idx - m + 1), min(n, curr_idx + 1)):
            if str1[start] == 'F':
                # check if this matches
                match = True
                for j in range(m):
                    char_in_ans = ans[start + j]
                    # if '-', it's not a full match yet
                    if char_in_ans == "-" or char_in_ans != str2[j]:
                        match = False
                        break
                if match:
                    return False
        return True