# 3161. Block Placement Queries

# There exists an infinite number line, with its origin at 0 and extending towards the positive x-axis.
# You are given a 2D array queries, which contains two types of queries:
# For a query of type 1, queries[i] = [1, x]. Build an obstacle at distance x from the origin. It is guaranteed that there is no obstacle at distance x when the query is asked.
# For a query of type 2, queries[i] = [2, x, sz]. Check if it is possible to place a block of size sz anywhere in the range [0, x] on the line, such that the block entirely lies in the range [0, x]. A block cannot be placed if it intersects with any obstacle, but it may touch it. Note that you do not actually place the block. Queries are separate.
# Return a boolean array results, where results[i] is true if you can place the block specified in the ith query of type 2, and false otherwise.

# Example 1:
# Input: queries = [[1,2],[2,3,3],[2,3,1],[2,2,2]]
# Output: [false,true,true]
# Explanation:
# For query 0, place an obstacle at x = 2. A block of size at most 2 can be placed before x = 3.

# Example 2:
# Input: queries = [[1,7],[2,7,6],[1,2],[2,7,5],[2,7,6]]
# Output: [true,true,false]
# Explanation:
# Place an obstacle at x = 7 for query 0. A block of size at most 7 can be placed before x = 7.
# Place an obstacle at x = 2 for query 2. Now, a block of size at most 5 can be placed before x = 7, and a block of size at most 2 before x = 2.

# Constraints:
# 1 <= queries.length <= 15 * 104
# 2 <= queries[i].length <= 3
# 1 <= queries[i][0] <= 2
# 1 <= x, sz <= min(5 * 104, 3 * queries.length)
# The input is generated such that for queries of type 1, no obstacle exists at distance x when the query is asked.
# The input is generated such that there is at least one query of type 2.

from sortedcontainers import SortedList

class SegmentTree:
    def __init__(self, size):
        self.n = 1
        while self.n < size:
            self.n *= 2
        self.tree = [0] * (2 * self.n)

    def update(self, i, val):
        i += self.n
        self.tree[i] = val
        while i > 1:
            i //= 2
            self.tree[i] = max(self.tree[2 * i], self.tree[2 * i + 1])

    def query(self, l, r):
        # Range Max Query [l, r)
        res = 0
        l += self.n
        r += self.n
        while l < r:
            if l % 2 == 1:
                res = max(res, self.tree[l])
                l += 1
            if r % 2 == 1:
                r -= 1
                res = max(res, self.tree[r])
            l //= 2
            r //= 2
        return res

class Solution(object):
    def getResults(self, queries):
        """
        :type queries: List[List[int]]
        :rtype: List[bool]
        """
        limit = min(50001, max(q[1] for q in queries) + 1) # max is 50,000 from problem
        st = SegmentTree(limit)
        obstacles = SortedList([0, limit])
        
        results = []
        
        for q in queries:
            if q[0] == 1:
                x = q[1]
                # Find neighbors
                idx = obstacles.bisect_left(x)
                left = obstacles[idx-1]
                right = obstacles[idx]
                
                obstacles.add(x)
                
                # Update gaps: 
                # New gap starts at 'left' ending at 'x'
                # New gap starts at 'x' ending at 'right'
                st.update(left, x - left)
                st.update(x, right - x)
                
            else:
                _, x, sz = q
                # Find the obstacle immediately to the left of x
                idx = obstacles.bisect_left(x)
                prev_obstacle = obstacles[idx-1]
                
                # 1. Check max gap recorded at all obstacles before 'prev_obstacle'
                max_gap_before = st.query(0, prev_obstacle)
                
                # 2. Check the gap ending at x (distance from prev_obstacle to x)
                current_gap = x - prev_obstacle
                
                results.append(max(max_gap_before, current_gap) >= sz)
                
        return results
    
'''
Solution generated by Gemini.ai becuase I almost ran out of time. However, here is a description
of how it works:

Store the locations of the start and end of each obsticle
Using a Segment Tree, make note of the gap sizes available
Then loop thorugh the Queries and using the tree, determine if it will fit (checking gaps between
the obsticle and 0, as well as the max point and the containing obsticle)
'''