# 3116. Kth Smallest Amount With Single Denomination Combination

# You are given an integer array coins representing coins of different denominations and an integer k.
# You have an infinite number of coins of each denomination. However, you are not allowed to combine coins of different denominations.
# Return the kth smallest amount that can be made using these coins.

# Example 1:
# Input: coins = [3,6,9], k = 3
# Output: 9
# Explanation: The given coins can make the following amounts:
# Coin 3 produces multiples of 3: 3, 6, 9, 12, 15, etc.
# Coin 6 produces multiples of 6: 6, 12, 18, 24, etc.
# Coin 9 produces multiples of 9: 9, 18, 27, 36, etc.
# All of the coins combined produce: 3, 6, 9, 12, 15, etc.

# Example 2:
# Input: coins = [5,2], k = 7
# Output: 12
# Explanation: The given coins can make the following amounts:
# Coin 5 produces multiples of 5: 5, 10, 15, 20, etc.
# Coin 2 produces multiples of 2: 2, 4, 6, 8, 10, 12, etc.
# All of the coins combined produce: 2, 4, 5, 6, 8, 10, 12, 14, 15, etc.

# Constraints:
# 1 <= coins.length <= 15
# 1 <= coins[i] <= 25
# 1 <= k <= 2 * 109
# coins contains pairwise distinct integers.

class Solution(object):
    def findKthSmallest(self, coins, k):
        """
        :type coins: List[int]
        :type k: int
        :rtype: int
        """
        low = min(coins)
        high = min(coins) * k
        ans = high

        # Binary search over the search space
        while low <= high:
            mid = (low + high) // 2
            
            if self.count_amounts(mid, coins) >= k:
                ans = mid
                high = mid - 1  # Try to find a smaller valid amount
            else:
                low = mid + 1  # Not enough amounts generated, need a larger upper bound

        return ans

    def gcd(self, a, b):
        '''
        Euluer Method
        '''
        while b:
            a, b = b, a % b
        return a

    def lcm(self, a, b):
        '''
        Greatest common multiple
        '''
        if a == 0 or b == 0:
            return 0
        return (a * b) // self.gcd(a, b)

    def count_amounts(self, x, coins):
        cnt = 0
        n = len(coins)
        
        # Loop through all non-empty subsets using bitmask
        for i in range(1, 1 << n):
            v = 1
            subset_size = 0
            
            for j in range(n):
                if (i >> j) & 1:
                    v = self.lcm(v, coins[j])
                    subset_size += 1
                    if v > x:
                        break
            
            # If LCM exceeds x, it contributes nothing
            if v > x:
                continue
                
            # Inclusion-Exclusion rule: add if odd size, subtract if even size
            if subset_size % 2 == 1:
                cnt += x // v
            else:
                cnt -= x // v
                
        return cnt

    '''
    I completely umnderstand all plinciples, but the code itself was generated by Gemini.ai
    following my inbtuition prompts.
    '''



'''
As expected, simple logic fails here (when jus brutee forcing the value generation in to an ordered list)
, due to array size and general time comkplexity
'''
class Solution(object):
    def findKthSmallest(self, coins, k):
        """
        :type coins: List[int]
        :type k: int
        :rtype: int
        """
        ans = set()
        for i in coins:
            for x in range(1,k+1):
                ans.add(i * x)

        sorted_ans = sorted(ans)
        return sorted_ans[k-1]