# 3312. Sorted GCD Pair Queries

# You are given an integer array nums of length n and an integer array queries.
# Let gcdPairs denote an array obtained by calculating the GCD of all possible pairs (nums[i], nums[j]), where 0 <= i < j < n, and then sorting these values in ascending order.
# For each query queries[i], you need to find the element at index queries[i] in gcdPairs.
# Return an integer array answer, where answer[i] is the value at gcdPairs[queries[i]] for each query.
# The term gcd(a, b) denotes the greatest common divisor of a and b.

# Example 1:
# Input: nums = [2,3,4], queries = [0,2,2]
# Output: [1,2,2]
# Explanation:
# gcdPairs = [gcd(nums[0], nums[1]), gcd(nums[0], nums[2]), gcd(nums[1], nums[2])] = [1, 2, 1].
# After sorting in ascending order, gcdPairs = [1, 1, 2].
# So, the answer is [gcdPairs[queries[0]], gcdPairs[queries[1]], gcdPairs[queries[2]]] = [1, 2, 2].

# Example 2:
# Input: nums = [4,4,2,1], queries = [5,3,1,0]
# Output: [4,2,1,1]
# Explanation:
# gcdPairs sorted in ascending order is [1, 1, 1, 2, 2, 4].

# Example 3:
# Input: nums = [2,2], queries = [0,0]
# Output: [2,2]
# Explanation:
# gcdPairs = [2].

# Constraints:
# 2 <= n == nums.length <= 105
# 1 <= nums[i] <= 5 * 104
# 1 <= queries.length <= 105
# 0 <= queries[i] < n * (n - 1) / 2

'''
Initial approach: Just do as the question asks

Issues:
This results in a time limit exceeded error (as expected). This is because the number of pairs
that is possible is O(n^2) with the addition of O(m) queries. Given n can be as large as 10^5, this
results in a worse case of O(10^10) which is way too large.
'''
class Solution(object):
    def gcdValues(self, nums, queries):
        """
        :type nums: List[int]
        :type queries: List[int]
        :rtype: List[int]
        """
        def gcd(a, b):
            while b:
                a, b = b, a % b
            return a

        gcdPairs = []
        #form the gcdPairs
        for posi, i in enumerate(nums):
            for posj, j in enumerate(nums):
                if posj > posi:
                    #this fufills the requirements so add it to gcdPairs
                    gcdPairs.append(gcd(i,j))
        
        gcdPairs.sort()
        
        #process queries
        ans = []
        for q in queries:
            ans.append(gcdPairs[q])

        return ans

'''
Issue Resolution:
Since the maximum value in nums is considerably smaller 5x10^4.
Calculate the number of pairs that can be formed fro each possible GCD value (taking into account
some pairs having th esame value as well as the fact some pairs can have a GCD that is a multiple
of another GCD)
    Working back from this value can eliminate the possible GCD values for that pair
    and reduce the number of pairs that can be formed for each GCD value.

While this all makes logical sense, I would not have been able to get to this solution without 
the use of Gemini.ai (code generated by them)
'''
import bisect

class Solution(object):
    def gcdValues(self, nums, queries):
        max_val = max(nums)
        
        # 1. Count frequencies of each number in nums
        freq = [0] * (max_val + 1)
        for x in nums:
            freq[x] += 1
            
        # 2. Count how many pairs have a GCD that is EXACTLY g
        gcd_count = [0] * (max_val + 1)
        
        for g in range(max_val, 0, -1):
            multiples_count = 0
            # how many multiples of g are there in nums? (including g itself)
            for k in range(g, max_val + 1, g):
                multiples_count += freq[k]
            
            #number of pairs that can be formed from multiples_count elements is C(multiples_count, 2)
            total_pairs = (multiples_count * (multiples_count - 1)) // 2
            
            minus_pairs = 0
            # subtract the pairs that have a GCD that is a multiple of g (i.e., 2g, 3g, ...)
            for k in range(2 * g, max_val + 1, g):
                minus_pairs += gcd_count[k]
                
            gcd_count[g] = total_pairs - minus_pairs

        # 3. Build the prefix sum boundaries along with their specific GCD values
        boundaries = []
        gcd_values = []
        current_total = 0
        
        # For each GCD value g, if there are pairs with that GCD, add the cumulative count to boundaries and store g in gcd_values
        for g in range(1, max_val + 1):
            if gcd_count[g] > 0:
                current_total += gcd_count[g]
                boundaries.append(current_total)
                gcd_values.append(g)
                
        # 4. Answer each query using binary search on the explicit boundaries
        ans = []
        for q in queries:
            # bisect_right finds the first index where boundary > q
            idx = bisect.bisect_right(boundaries, q)
            # Map that index directly to the actual GCD value stored at the same position
            ans.append(gcd_values[idx])
            
        return ans