# 3661. Maximum Walls Destroyed by Robots

# There is an endless straight line populated with some robots and walls. You are given integer arrays robots, distance, and walls:
# robots[i] is the position of the ith robot.
# distance[i] is the maximum distance the ith robot's bullet can travel.
# walls[j] is the position of the jth wall.
# Every robot has one bullet that can either fire to the left or the right at most distance[i] meters.
# A bullet destroys every wall in its path that lies within its range. Robots are fixed obstacles: if a bullet hits another robot before reaching a wall, it immediately stops at that robot and cannot continue.
# Return the maximum number of unique walls that can be destroyed by the robots.
# Notes:
# A wall and a robot may share the same position; the wall can be destroyed by the robot at that position.
# Robots are not destroyed by bullets.

# Example 1:
# Input: robots = [4], distance = [3], walls = [1,10]
# Output: 1
# Explanation:
# robots[0] = 4 fires left with distance[0] = 3, covering [1, 4] and destroys walls[0] = 1.
# Thus, the answer is 1.

# Example 2:
# Input: robots = [10,2], distance = [5,1], walls = [5,2,7]
# Output: 3
# Explanation:
# robots[0] = 10 fires left with distance[0] = 5, covering [5, 10] and destroys walls[0] = 5 and walls[2] = 7.
# robots[1] = 2 fires left with distance[1] = 1, covering [1, 2] and destroys walls[1] = 2.
# Thus, the answer is 3.

# Example 3:
# Input: robots = [1,2], distance = [100,1], walls = [10]
# Output: 0
# Explanation:
# In this example, only robots[0] can reach the wall, but its shot to the right is blocked by robots[1]; thus the answer is 0.

# Constraints:
# 1 <= robots.length == distance.length <= 105
# 1 <= walls.length <= 105
# 1 <= robots[i], walls[j] <= 109
# 1 <= distance[i] <= 105
# All values in robots are unique
# All values in walls are unique



#   THIS WAS MY INITIAL APPROACH WHICH FAILED DUE TO NOT ACOUNTING FOR THE DISTRUCTION OF
#   RANGE DUE TO OTHER ROBOTS
# the issue in this was selecting what which direction from each robot should be aselected
# to get a maximun solution
import bisect

class Solution(object):
    def maxWalls(self, robots, distance, walls):
        """
        :type robots: List[int]
        :type distance: List[int]
        :type walls: List[int]
        :rtype: int
        """
        # sort walls and robots
        # Pairing distance with robots is essential
        robot_data = sorted(zip(robots, distance))
        walls.sort()

        #define the max range left and right for each robot (distance between robot pairs)
        num_robots = len(robots)
        total_destroyed = 0
        last_wall_idx = 0 # Pointer to the first wall that hasn't been destroyed yet

        #use the distance seporation to determine the actual ranges
        for i in range(num_robots):
            curr_pos, curr_dist = robot_data[i]

            # left neighbour boundary
            if i == 0:
                left_limit = float('-inf')
            else:
                left_limit = robot_data[i-1][0]
            
            # right neighbour boundary
            if i == num_robots - 1:
                right_limit = float('inf')
            else:
                right_limit = robot_data[i+1][0]
            
            # get the closest location (either another robot or range runs out)
            actual_left = max(left_limit, curr_pos - curr_dist)
            actual_right = min(right_limit, curr_pos + curr_dist)
            
            # Binary search to find the number of walls
            # We use lo=last_wall_idx to ensure we never look at a wall 
            # that was already claimed by a previous robot.
            idx_start = bisect.bisect_left(walls, actual_left, lo=last_wall_idx)
            idx_end = bisect.bisect_right(walls, actual_right, lo=idx_start)
            
            # keep a running total of unique walls distroyed
            count = idx_end - idx_start
            total_destroyed += count
            
            # Update the pointer to the end of this robot's harvest
            last_wall_idx = idx_end

        return total_destroyed
    






# this solution was generated by claude.ai
# this aims to choose which direction from each robot by compairing the solusions
# for each direction. This checks to see if firing in the same direction (rather
# than always choosing alternating) is worth it to form an overall solution
# E.G. if 2 fire towards eachother and distroy 10, might be better than the left destroying 6
#   and the right destroying 5 (total 11) so that the next one can get the full 7 rather then the
#   other choice of 1. Have to choose for the greater good.

#I understand all ideas and principles, and propted it to head in this direction efficiently.

from bisect import bisect_left, bisect_right

class Solution(object):
    def maxWalls(self, robots, distance, walls):
        """
        :type robots: List[int]
        :type distance: List[int]
        :type walls: List[int]
        :rtype: int
        """
        bots = sorted(zip(robots, distance), key=lambda x: x[0])
        sorted_walls = sorted(walls)
        n = len(bots)

        def count_walls(lo, hi):
            if lo > hi:
                return 0
            return bisect_right(sorted_walls, hi) - bisect_left(sorted_walls, lo)

        def count_walls_exclusive(lo, hi, exclude_lo, exclude_hi):
            """Count walls in [lo,hi] but NOT in [exclude_lo, exclude_hi]."""
            if lo > hi:
                return 0
            total = count_walls(lo, hi)
            if exclude_lo > hi or exclude_hi < lo:
                return total
            overlap_lo = max(lo, exclude_lo)
            overlap_hi = min(hi, exclude_hi)
            return total - count_walls(overlap_lo, overlap_hi)

        # eft and right ranges for each robot
        ranges = []
        for i, (pos, dist) in enumerate(bots):
            left_lo = pos - dist if i == 0 else max(pos - dist, bots[i-1][0] + 1)
            left_hi = pos
            right_lo = pos
            right_hi = pos + dist if i == n-1 else min(pos + dist, bots[i+1][0] - 1)
            ranges.append((left_lo, left_hi, right_lo, right_hi))

        # DP: dp[direction] = max walls if robot i fires in that direction        
        if n == 0:
            return 0

        ll0, lh0, rl0, rh0 = ranges[0]
        # dp[0] = fires left, dp[1] = fires right
        dp = [count_walls(ll0, lh0), count_walls(rl0, rh0)]

        for i in range(1, n):
            ll, lh, rl, rh = ranges[i]
            prev_ll, prev_lh, prev_rl, prev_rh = ranges[i-1]

            walls_i_left = count_walls(ll, lh)
            walls_i_right = count_walls(rl, rh)

            # Overlap between current robot's LEFT range and previous robot's RIGHT range
            # (these share the gap between the two robots)
            overlap_lo = max(ll, prev_rl)
            overlap_hi = min(lh, prev_rh)
            overlap = count_walls(overlap_lo, overlap_hi) if overlap_lo <= overlap_hi else 0

            new_dp = [0, 0]

            # Current fires LEFT
            # - prev fired LEFT: no overlap possible (prev right range doesn't touch current left range)
            new_dp[0] = max(new_dp[0], dp[0] + walls_i_left)
            # - prev fired RIGHT: subtract overlap (walls counted in both)
            new_dp[0] = max(new_dp[0], dp[1] + walls_i_left - overlap)

            # Current fires RIGHT
            # - prev fired LEFT: no overlap
            new_dp[1] = max(new_dp[1], dp[0] + walls_i_right)
            # - prev fired RIGHT: no overlap (prev right and current right don't overlap)
            new_dp[1] = max(new_dp[1], dp[1] + walls_i_right)

            dp = new_dp

        return max(dp)