# 3225. Maximum Score From Grid Operations

# You are given a 2D matrix grid of size n x n. Initially, all cells of the grid are colored white. In one operation, you can select any cell of indices (i, j), and color black all the cells of the jth column starting from the top row down to the ith row.
# The grid score is the sum of all grid[i][j] such that cell (i, j) is white and it has a horizontally adjacent black cell.
# Return the maximum score that can be achieved after some number of operations.

# Example 1:
# Input: grid = [[0,0,0,0,0],[0,0,3,0,0],[0,1,0,0,0],[5,0,0,3,0],[0,0,0,0,2]]
# Output: 11
# Explanation:
# In the first operation, we color all cells in column 1 down to row 3, and in the second operation, we color all cells in column 4 down to the last row. The score of the resulting grid is grid[3][0] + grid[1][2] + grid[3][3] which is equal to 11.

# Example 2:
# Input: grid = [[10,9,0,0,15],[7,1,0,8,0],[5,20,0,11,0],[0,0,0,1,2],[8,12,1,10,3]]
# Output: 94
# Explanation:
# We perform operations on 1, 2, and 3 down to rows 1, 4, and 0, respectively. The score of the resulting grid is grid[0][0] + grid[1][0] + grid[2][1] + grid[4][1] + grid[1][3] + grid[2][3] + grid[3][3] + grid[4][3] + grid[0][4] which is equal to 94.

# Constraints:
# 1 <= n == grid.length <= 100
# n == grid[i].length
# 0 <= grid[i][j] <= 109

'''
Using the Editorial, I was able to come up with somethign similar to this (theis code was generated by 
Claude.ai as mine had a few fault for syntax and i couldnt be bothered to write some sections becuase I
was Lazy). This idea/prompt points was all by me however, based on the Editorial (which I use to check
that I was on the right lines)
Issues: The below code hoever (despite correct results) resulting in a 'Time Limit Exceeded' error
so some optimisaiton is needed.
'''
class Solution(object):
    def maximumScore(self, grid):
        """
        :type grid: List[List[int]]
        :rtype: int
        """


        n = len(grid)
        # prefix sum calculation
        col_prefix = [[0] * (n + 1) for _ in range(n)]
        for j in range(n):
            for i in range(n):
                col_prefix[j][i + 1] = col_prefix[j][i] + grid[i][j]


        # helper: determining the heigh/value of a column value
        def col_sum(j, lo, hi):
            if j < 0 or j >= n or lo >= hi:
                return 0
            return col_prefix[j][hi] - col_prefix[j][lo]

        NEG = float('-inf') # holder

        dp = {}
        dp[(0, 0)] = 0

        for i in range(n):
            new_dp = {}
            for (h_prev, h_pprev), base in dp.items():
                if base == NEG:
                    continue
                for h_curr in range(n + 1):
                    if h_curr > h_prev:
                        #core col i-1 cells [max(h_prev,h_pprev)..h_curr-1]
                        #       (avoid cells already scored by col i-2)
                        if i == 0:
                            score = 0
                        else:
                            lo = max(h_prev, h_pprev)
                            score = col_sum(i - 1, lo, h_curr)
                    else:
                        # score col i white cells [h_curr..h_prev-1] adj to black col i-1
                        score = col_sum(i, h_curr, h_prev)

                    val = base + score
                    key = (h_curr, h_prev)
                    if new_dp.get(key, NEG) < val:
                        new_dp[key] = val

            dp = new_dp

        return max(dp.values()) if dp else 0


'''
Optimisation ideas:
- since the final row does not effect a next row, it can either be fully black or fully white to get
the optimal result
- the final column should be fully white as this would result in the optimal answer
'''

class Solution(object):
    def maximumScore(self, grid):
        """
        :type grid: List[List[int]]
        :rtype: int
        """
        n = len(grid)

        col_prefix = [[0] * (n + 1) for _ in range(n)]
        for j in range(n):
            for i in range(n):
                col_prefix[j][i + 1] = col_prefix[j][i] + grid[i][j]

        def col_sum(j, lo, hi):
            if j < 0 or j >= n or lo >= hi:
                return 0
            return col_prefix[j][hi] - col_prefix[j][lo]

        NEG = float('-inf')

        # dp[h_prev][h_pprev] = best score with last col height h_prev, before-last h_pprev
        dp = [[NEG] * (n + 1) for _ in range(n + 1)]
        dp[0][0] = 0

        for i in range(n):
            new_dp = [[NEG] * (n + 1) for _ in range(n + 1)]

            # Precompute for each h_prev:
            # 1. best_free[h_prev] = max over ALL h_pprev of dp[h_prev][h_pprev]
            #    (used when h_curr <= h_prev: score doesn't depend on h_pprev)
            # 2. max_below[h_prev] = max over h_pprev < h_prev of dp[h_prev][h_pprev]
            #    (used when h_curr > h_prev and h_pprev < h_prev: lo = h_prev)
            # 3. suf[h_prev][k] = max over h_pprev >= k of (dp[h_prev][h_pprev] - col_prefix[i-1][h_pprev])
            #    (used when h_curr > h_prev and h_pprev >= h_prev: lo = h_pprev)
            #    score = suf[h_prev][h_prev] + col_prefix[i-1][h_curr]

            best_free = [NEG] * (n + 1)
            max_below = [NEG] * (n + 1)

            # suffix max of (dp[h_prev][h_pprev] - col_prefix[i-1][h_pprev]) for h_pprev >= threshold
            # suf[h_prev][k] = max over h_pprev in [k..n]
            # We only need suf[h_prev][h_prev], so build per h_prev
            suf_at_hprev = [NEG] * (n + 1)  # suf_at_hprev[h_prev] = suf[h_prev][h_prev]

            for h_prev in range(n + 1):
                row = dp[h_prev]
                # best_free
                best_free[h_prev] = max(row)
                # max_below: max over h_pprev in [0..h_prev-1]
                mb = NEG
                for k in range(h_prev):
                    if row[k] > mb:
                        mb = row[k]
                max_below[h_prev] = mb
                # suf from h_prev upward
                if i > 0:
                    s = NEG
                    # suffix from n down to h_prev
                    for k in range(n, h_prev - 1, -1):
                        if row[k] != NEG:
                            v = row[k] - col_prefix[i-1][k]
                            if v > s:
                                s = v
                    suf_at_hprev[h_prev] = s

            for h_prev in range(n + 1):
                for h_curr in range(n + 1):
                    if h_curr <= h_prev:
                        # score col i white cells [h_curr..h_prev-1], no h_pprev dependency
                        base = best_free[h_prev]
                        if base == NEG:
                            continue
                        score = col_sum(i, h_curr, h_prev)
                        val = base + score
                        if val > new_dp[h_curr][h_prev]:
                            new_dp[h_curr][h_prev] = val

                    else:
                        # h_curr > h_prev
                        if i == 0:
                            # no col i-1 exists, score = 0
                            base = dp[h_prev][0] if h_prev == 0 else NEG
                            if base != NEG and base > new_dp[h_curr][h_prev]:
                                new_dp[h_curr][h_prev] = base
                            continue

                        best = NEG

                        # Case A: h_pprev < h_prev → lo = h_prev
                        # score = col_sum(i-1, h_prev, h_curr)
                        if max_below[h_prev] != NEG:
                            v = max_below[h_prev] + col_sum(i - 1, h_prev, h_curr)
                            if v > best:
                                best = v

                        # Case B: h_pprev >= h_prev → lo = h_pprev
                        # score = col_prefix[i-1][h_curr] - col_prefix[i-1][h_pprev]
                        # val = dp[h_prev][h_pprev] - col_prefix[i-1][h_pprev] + col_prefix[i-1][h_curr]
                        # = suf_at_hprev[h_prev] + col_prefix[i-1][h_curr]
                        if suf_at_hprev[h_prev] != NEG:
                            v = suf_at_hprev[h_prev] + col_prefix[i - 1][h_curr]
                            if v > best:
                                best = v

                        if best > new_dp[h_curr][h_prev]:
                            new_dp[h_curr][h_prev] = best

            dp = new_dp

        # Optimisation: last column should be h=0 (fully white) or h=n (fully black)
        # as it doesn't affect future columns — only extreme values can be optimal
        ans = 0
        for h_pprev in range(n + 1):
            for h in [0, n]:
                v = dp[h][h_pprev]
                if v != NEG and v > ans:
                    ans = v
        return ans
    
'''
While my optimisations were correct, I was unable to think of any other areas to make it better.
Once again I asked Claude.ai for some help

Summary:
The trick is noticing that when computing the transition, h_pprev only matters in one place: the max(h_prev, h_pprev)
that determines where the scoring starts. This creates exactly two cases:
    - h_pprev < h_prev: max(h_prev, h_pprev) = h_prev, so the score col_sum(i-1, h_prev, h_curr) is the same regardless of which
    specific h_pprev was used. So instead of trying every h_pprev < h_prev, you just need the single best dp[h_prev][h_pprev]
    across all of them — that's max_below[h_prev], precomputed once in O(n).

    - h_pprev >= h_prev: max(h_prev, h_pprev) = h_pprev, so the score is col_prefix[i-1][h_curr] - col_prefix[i-1][h_pprev].
    Rearranging: val = (dp[h_prev][h_pprev] - col_prefix[i-1][h_pprev]) + col_prefix[i-1][h_curr]. The first bracket depends
    only on h_pprev, the second only on h_curr. So you precompute the suffix max of dp[h_prev][h_pprev] - col_prefix[i-1][h_pprev]
    over all h_pprev >= h_prev — that's suf_at_hprev[h_prev], again O(n) — and then the transition is O(1).
'''