# 2976. Minimum Cost to Convert String 1

# You are given two 0-indexed strings source and target, both of length n and consisting of lowercase English letters.
# You are also given two 0-indexed character arrays original and changed, and an integer array cost, where cost[i] represents
# the cost of changing the character original[i] to the character changed[i].
# You start with the string source. In one operation, you can pick a character x from the string and change it to the character
# y at a cost of z if there exists any index j such that cost[j] == z, original[j] == x, and changed[j] == y.
# Return the minimum cost to convert the string source to the string target using any number of operations. If it is impossible
# to convert source to target, return -1.
# Note that there may exist indices i, j such that original[j] == original[i] and changed[j] == changed[i].


# Example 1:
# Input: source = "abcd", target = "acbe", original = ["a","b","c","c","e","d"], changed = ["b","c","b","e","b","e"], cost = [2,5,5,1,2,20]
# Output: 28
# Explanation: To convert the string "abcd" to string "acbe":
# - Change value at index 1 from 'b' to 'c' at a cost of 5.
# - Change value at index 2 from 'c' to 'e' at a cost of 1.
# - Change value at index 2 from 'e' to 'b' at a cost of 2.
# - Change value at index 3 from 'd' to 'e' at a cost of 20.
# The total cost incurred is 5 + 1 + 2 + 20 = 28.
# It can be shown that this is the minimum possible cost.

# Example 2:
# Input: source = "aaaa", target = "bbbb", original = ["a","c"], changed = ["c","b"], cost = [1,2]
# Output: 12
# Explanation: To change the character 'a' to 'b' change the character 'a' to 'c' at a cost of 1, followed by changing the character 'c' to 'b' at a cost of 2, for a total cost of 1 + 2 = 3. To change all occurrences of 'a' to 'b', a total cost of 3 * 4 = 12 is incurred.

# Example 3:
# Input: source = "abcd", target = "abce", original = ["a"], changed = ["e"], cost = [10000]
# Output: -1
# Explanation: It is impossible to convert source to target because the value at index 3 cannot be changed from 'd' to 'e'.


# Constraints:
# 1 <= source.length == target.length <= 105
# source, target consist of lowercase English letters.
# 1 <= cost.length == original.length == changed.length <= 2000
# original[i], changed[i] are lowercase English letters.
# 1 <= cost[i] <= 106
# original[i] != changed[i]


class Solution(object):
    def minimumCost(self, source, target, original, changed, cost):
        """
        :type source: str
        :type target: str
        :type original: List[str]
        :type changed: List[str]
        :type cost: List[int]
        :rtype: int
        """
        #1. form a map from original to changed such that you can get from every input to every output
        # to give a minimum cost - required O(n x n) space - you can use an algorithm like Floyd-Warshall
        #2. go thought the input and map it ot the output, taking the minimum cost from the table

        # ===== PHASE 1 =====
        #initialise array with all transitions being infinite
        INF = float('inf')
        dist = [[INF] * 26 for _ in range(26)]
        #diagonals are 0's
        for i in range(26):
            dist[i][i] = 0
        #add in the direct transitions
        for i in range(len(original)):
            x = ord(original[i]) - ord('a')
            y = ord(changed[i]) - ord('a')
            dist[x][y] = min(dist[x][y], cost[i])
        
        #perform the looping to go through all transitions / minimum cost for all pairs
        for k in range(26):  # intermediate vertex
            for i in range(26):  # source
                for j in range(26):  # destination
                    dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j])

        #=====PHASE 2=====
        #go thorugh and see what transitions you can do to make them match and returnt eh minimum
        total_cost = 0
        for i in range(len(source)):
            if source[i] == target[i]: #no change needed
                continue
            
            x = ord(source[i]) - ord('a')
            y = ord(target[i]) - ord('a')
            
            if dist[x][y] == INF:
                return -1  # Impossible to transform
            
            total_cost += dist[x][y]
        
        return total_cost

#all code was generated by Claud however, i checked it over myself and the logic was me
# (i just couldnt be bothered to type it out)
#I proviede the alogrithm choice with no help and knew exactly howto implement and how to do it
#   it was my choice to use Floyd-Warshall and i understood the need for it

# Complexity Analysis:
# Time Complexity: O(N^3 + M), where N is the number of characters in the alphabet (26 for lowercase English letters)
# howeverm in this case, there is a far larger input size (26) as  did not specify that there will only exist transitions
# for the present characters in the source and target strings.
# Space Complexity: O(N^2) for the distance matrix. In this case, O(26^2) which is effectively constant space.



# to be more effiencent, rather than looking at transitions for the entire alphabet, we could just look at the characters present
# in the source and target strings
# this would reduce the compleity from O(26^3 + M) to O(C^3 + M) where C < 26
# BEYOND SCOPE IMPORVEMNT:
# this would also mean that this is more adaptable as I would work for any charatcer set, not just lowercase English letters

#bellow is the claud generated code for this problem - all primciples are mine however
#initialise array with all transitions being infinite
class Solution(object):
    def minimumCost(self, source, target, original, changed, cost):
        # Step 1: Find all unique characters we need to consider
        all_chars = set(source) | set(target) | set(original) | set(changed)
        
        # Create a mapping from character to index
        char_to_idx = {char: i for i, char in enumerate(sorted(all_chars))}
        n = len(char_to_idx)
        
        # Initialize cost matrix (n x n, where n is number of unique chars)
        INF = float('inf')
        dist = [[INF] * n for _ in range(n)]
        
        # Cost to transform a letter to itself is 0
        for i in range(n):
            dist[i][i] = 0
        
        # Add direct transformation costs
        for i in range(len(original)):
            x = char_to_idx[original[i]]
            y = char_to_idx[changed[i]]
            dist[x][y] = min(dist[x][y], cost[i])  # Take minimum if duplicate
        
        # Step 2: Floyd-Warshall - find minimum costs for all pairs
        for k in range(n):  # intermediate vertex
            for i in range(n):  # source
                for j in range(n):  # destination
                    dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j])
        
        # Step 3: Calculate total cost for transformation
        total_cost = 0
        for i in range(len(source)):
            if source[i] == target[i]:
                continue  # No change needed
            
            x = char_to_idx[source[i]]
            y = char_to_idx[target[i]]
            
            if dist[x][y] == INF:
                return -1  # Impossible to transform
            
            total_cost += dist[x][y]
        
        return total_cost