#code generated by Claud - simply for understanding on why my previous method fails on a large input
#3454. Separate Squares 2

# You are given a 2D integer array squares. Each squares[i] = [xi, yi, li] represents the 
# coordinates of the bottom-left point and the side length of a square parallel to the x-axis.

# Find the minimum y-coordinate value of a horizontal line such that the total area covered by squares above the line equals the total area covered by squares below the line.

# Answers within 10-5 of the actual answer will be accepted.

# Note: Squares may overlap. Overlapping areas should be counted only once in this version.

class SegmentTree:
    """Segment tree for tracking union of x-intervals"""
    def __init__(self, x_coords):
        self.x_coords = x_coords
        n = len(x_coords) - 1
        self.cnt = [0] * (4 * n)  # Count of active squares covering each node
        self.length = [0.0] * (4 * n)  # Total length covered in this node
    
    def update(self, idx, left, right, ql, qr, val, node=0):
        """Update interval [ql, qr) by adding val"""
        if right <= ql or qr <= left:
            return
        
        if ql <= left and right <= qr:
            self.cnt[node] += val
        else:
            mid = (left + right) // 2
            self.update(idx, left, mid, ql, qr, val, 2 * node + 1)
            self.update(idx, mid, right, ql, qr, val, 2 * node + 2)
        
        self._pushup(node, left, right)
    
    def _pushup(self, node, left, right):
        """Update length based on children"""
        if self.cnt[node] > 0:
            # This entire range is covered
            self.length[node] = self.x_coords[right] - self.x_coords[left]
        elif left + 1 == right:
            # Leaf node with no coverage
            self.length[node] = 0.0
        else:
            # Sum of children
            self.length[node] = self.length[2 * node + 1] + self.length[2 * node + 2]
    
    def query(self):
        """Get total length of union"""
        return self.length[0]


class Solution(object):
    def separateSquares(self, squares):
        """
        :type squares: List[List[int]]
        :rtype: float
        """
        if not squares:
            return 0.0
        
        # Step 1: Create events
        events = []
        for x, y, l in squares:
            events.append((y, 1, x, x + l))      # Start event
            events.append((y + l, -1, x, x + l))  # End event
        
        # Step 2: Sort events by y-coordinate
        events.sort()
        
        # Step 3: Coordinate compression
        x_coords = set()
        for _, _, x_start, x_end in events:
            x_coords.add(x_start)
            x_coords.add(x_end)
        x_coords = sorted(x_coords)
        x_to_idx = {x: i for i, x in enumerate(x_coords)}
        
        # Step 4: Single pass with segment tree
        seg_tree = SegmentTree(x_coords)
        n = len(x_coords)
        
        total_area = 0.0
        cumulative_area = 0.0
        prev_y = events[0][0]
        target_found = False
        result_y = 0.0
        
        for y, event_type, x_start, x_end in events:
            # Calculate area between prev_y and current y
            if y > prev_y:
                width = seg_tree.query()
                height = y - prev_y
                area = width * height
                
                total_area += area
                
                # Check if we haven't found target yet
                if not target_found:
                    # We need to delay target calculation until we know total_area
                    cumulative_area += area
            
            # Update segment tree
            start_idx = x_to_idx[x_start]
            end_idx = x_to_idx[x_end]
            seg_tree.update(0, 0, n - 1, start_idx, end_idx, event_type)
            
            prev_y = y
        
        # Step 5: Second pass to find split line (now that we know total_area)
        target_area = total_area / 2.0
        seg_tree = SegmentTree(x_coords)
        cumulative_area = 0.0
        prev_y = events[0][0]
        
        for y, event_type, x_start, x_end in events:
            if y > prev_y:
                width = seg_tree.query()
                height = y - prev_y
                area = width * height
                
                # Check if we cross the halfway point
                if cumulative_area + area >= target_area:
                    remaining = target_area - cumulative_area
                    if width > 0:
                        return prev_y + remaining / width
                    else:
                        return prev_y
                
                cumulative_area += area
            
            # Update segment tree
            start_idx = x_to_idx[x_start]
            end_idx = x_to_idx[x_end]
            seg_tree.update(0, 0, n - 1, start_idx, end_idx, event_type)
            
            prev_y = y
        
        return prev_y
